Monash-FIT3170/Shazam-3-Scrum-Unleashed

README.md
=> add team member name

README.md
=> Adding my details to the README.md file

README.md
=> Added name to ReadMe

frontend/package-lock.json, frontend/package.json
yeah i just ran npm install react-bootstrap bootstrap thats all
=> added react bootstrap

README.md, frontend/README.md, frontend/src/classes/player.ts
the readme wasnt in the top level directory so github couldn't detect and display it properly. also added a note about formatting and linting
=> Aabb0010 fixing readme location

frontend/src/classes/tournamentManager.ts
created the tournament manager, and created a couple methods that might be needed for it
=> created a tournament manager

README.md
=> Updated ReadMe file 

frontend/package-lock.json, frontend/package.json
just ran npm install socket.io thats all
=> added socket

client/package-lock.json, client/package.json, client/src/App.tsx, client/src/pages/Home.tsx, client/src/pages/HostGame.tsx, client/src/pages/JoinGame.tsx, client/src/pages/PagePaths.ts, client/vite.config.ts, server/server.ts, types/socket/events.ts
Also added a basic HostGame page and hooked that up with the server via sockets.
=> Added Page Routing to ReactJS Frontend

client/src/pages/JoinGame.tsx
In join-game page: 
Decreased size of logo and added flex-col to position elements nicely.
=> bugfix: join game  UI 

client/src/App.tsx, server/server.ts, server/socket/sessionStore.ts, types/socket/events.ts
- Implemented persistent sessions so that the user will be reconnected to the same session and have access to the previous information.
- Typing error in server.ts line 42, which I couldn't fix.
- I believe we also now need to always emit events to the room (based on sessionID), rather then to a socket.id.
=> feature: implemented persistent sessions 

client/src/components/ChoosePlayerMove.tsx, client/src/components/CountDownTimer.tsx, client/src/components/MoveSelection.tsx, client/src/components/WaitingToStart.tsx, client/src/pages/PlayerScreen.tsx, server/model/gameSessionManager.ts, server/socketRoomManager.ts, types/socket/events.ts
* Multiple duels can be played concurrently among multiple rooms
* Duels are replayed when a draw occurs
* Components are dynamically rendered in PlayerScreen class. 
* Still need to integrate with UI
=> feature: duel socket functionality

client/src/App.css, client/src/App.tsx, client/src/components/PlayerCard.tsx, client/src/loaders/index.ts, client/src/pages/GameLobby.tsx, client/src/pages/TournamentScreen.tsx, server/model/game.ts, server/model/tournamentManager.ts, server/server.ts, server/socketRoomManager.ts, types/socket/events.ts
Contains the logic for the host to navigate to tournament screen after they start the tournament.
- added a button to the Game Lobby screen which starts the game and navigates to tournament screen
- tournament takes player list from game rather than a sample hard coded list of players
- added player list UI to Game Lobby screen
=> feature: connecting tournament screen

client/src/components/PlayerMoveHand.tsx, client/src/components/reactions/ReactionsOverlay.tsx, client/src/pages/PlayerScreen.tsx, server/src/controllers/helper/roundHelper.ts, server/src/controllers/socket/addReaction.ts, server/src/controllers/socket/chooseAction.ts, server/src/controllers/socket/startTournament.ts, server/src/model/player.ts, server/src/server.ts, types/socket/events.ts, types/types.ts
=> feature: implemented specators and reactions

client/src/components/lobby/PlayerCard.tsx, client/src/components/player-screen/match-overlay/PlayerAndSpectatorsInfo.tsx, server/src/controllers/helper/roundHelper.ts, server/src/controllers/socket/startTournament.ts, server/src/emitters/roundStartEmitter.ts, server/src/model/match.ts, server/src/model/player.ts, server/src/server.ts, types/socket/events.ts, types/types.ts
=> refactor: clean up spectators logic

client/index.html
Added Google tags for Google Analytics
=> feature: Google Analytics

client/src/components/pong/Pong.tsx, server/src/model/matches/pongMatch.ts, server/src/server.ts
Ball animates on client between server pings
=> feature: client side smoothing

client/src/components/pong/Pong.tsx
Mirror canvas not css transform + fix conditional for both sides
=> ehc: pong optimisations

client/src/pages/GameMenu.tsx
Added a back button to tournament creation, which allows a user to return to the home page from the create tournament page
=> Added a back button on create tournament screen

client/src/assets/misc/Close.svg, client/src/assets/misc/OutlinedError.svg, client/src/components/ErrorBanner.tsx, client/src/components/buttons/FormButton.tsx, client/src/components/player-screen/tournament-win/TournamentWin.tsx, client/src/pages/JoinTournament.tsx, server/src/controllers/http/joinTournamentHandler.ts, types/requestTypes.ts, types/socket/eventArguments.ts, types/socket/events.ts, types/types.ts
Added Error banner to to the Join Game page, no longer have to refresh when an error occurs (user name taken, incorrect code, inappropriate name, etc)
=> feature: join game error handling

client/src/pages/PlayerScreen.tsx
* Sandy's duel animation plays when the host starts the game. 
*  Uses localstorage so it only plays once  per tournament 
* It will play for Pong game as well.
=> feature: Added duel animation to start of game

client/src/components/lobby/HostSpectatorScreen.tsx, client/src/components/player-screen/match-overlay/PlayerAndSpectatorsInfo.tsx, client/src/components/player-screen/match-overlay/StarsInfo.tsx, client/src/components/player-screen/outcome-screens/DuelOutcome.tsx, client/src/components/player-screen/outcome-screens/DuelOutcomeText.tsx, client/src/components/player-screen/outcome-screens/MatchOutcomeScreen.tsx, client/src/components/rps/RPS.tsx, client/src/pages/PlayerScreen.tsx
* Border is white not green for some reason
=> Feature: Fix duel text for spectators and added border 

client/src/App.css, client/src/components/buttons/FormButton.tsx, client/src/components/inputs/InputComponent.tsx, client/src/components/lobby/TournamentLobbyBanner.tsx, client/src/pages/CreateTournament.tsx, client/src/pages/JoinTournament.tsx, client/src/pages/PlayerScreen.tsx
- also changed the link in the tournament lobby banner to actually work
- join screen should dynamically change the button and input sizes to fit the screen given the screen isn't 2px wide
=> Bugfix: Fixing mobile view for join screen

server/src/controllers/helper/roundHelper.ts, server/src/controllers/http/joinTournamentHandler.ts, server/src/controllers/http/startTournamentHandler.ts, server/src/emitters/roundStartEmitter.ts, server/src/model/tournament.ts, server/src/utils/reconnectionHelper.ts
fixed join in progress game and host screen reconnecting befo…re starting a game.
=> bugfix: additional tournament joining checks

client/src/components/lobby/HostSpectatorScreen.tsx, client/src/components/player-screen/match-overlay/PlayerAndSpectatorsInfo.tsx, client/src/components/player-screen/match-overlay/StarsInfo.tsx, client/src/components/player-screen/outcome-screens/DuelOutcome.tsx, client/src/components/player-screen/outcome-screens/DuelOutcomeText.tsx, client/src/components/player-screen/outcome-screens/MatchOutcomeScreen.tsx, client/src/components/rps/RPS.tsx, client/src/pages/PlayerScreen.tsx
Added back the improvements after they were accidently deleted.
=> feature: specator UI improvements

server/src/controllers/helper/roundHelper.ts, server/src/controllers/socket/chooseAction.ts, server/src/model/matches/match.ts, server/src/model/matches/pongMatch.ts, server/src/model/matches/rpsMatch.ts, server/src/model/tournament.ts
No actual timer is being displayed, is only a backend timer.
=> feature: round timeout to prevent rounds from lasting forever added

client/src/components/pong/Pong.tsx
I'd like to thank the one that starts with C and ends in laude
=> Optimise pong game

client/package-lock.json, client/src/components/inputs/ChooseMatchType.tsx, client/src/components/inputs/CreateTournamentInput.tsx, client/src/pages/CreateTournament.tsx, server/package-lock.json
Added images and increased the size of icons in the create game page.
=> Made create game page look nicer

client/src/components/pong/Pong.tsx
kinda dogshit, but kinda goated
=> transition ball

client/src/components/player-screen/choose-move/ChoosePlayerMove.tsx, client/src/components/player-screen/choose-move/MoveSelection.tsx, client/src/components/rps/RPS.tsx, server/src/controllers/socket/chooseAction.ts, server/src/model/matches/rpsMatch.ts, types/socket/events.ts, types/types.ts
Continued to work on RPS power up, change how they are spawned slightly and consolidated the RPS messsages.
=> feature: RPS power up continued
